### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by wlrhnh-David** [Assuner-Lee/dna#1]
test() async {
    JAVAContext context = new JAVAContext();
    NativeObject version = context
        .newJavaObjectFromConstructor('java.lang.String', ["android "]);
    Log.d('version = $version');
  }

以Android为例，写了这么几行，打印出来的是Instance of 'JavaObjectConstructor'

还有如何创建Native的类呢，比如DnaTest及getVersion()方法这样的？

**Comment by Assuner-Lee** [comment]
最终需要执行context.execute()来把上下文传给原生并执行；另外，dna不能创建原生类，只能调用已存在的类的方法
