### ISSUE TITLE
增加自动根据jar生成Binding代码的功能

### ISSUE THREAD

**Issue by chinshou** [Assuner-Lee/dna#2]
在Delphi里面提供了通过对jar的class文件的解析自动生成binding的代码,然后通过反射来调用android的java的api
class解析参考repository
https://github.com/ying32/JavaClassToDelphiUnit
否则现在这种所有的调用代码都要手工去写,节省工作量不是很高,并且很容易出错.

Objective-C的自动binding代码的实现, Delphi里面也提供了,原理是用libClang来解析ObjectiveC的framework中的头文件, 然后自动生成binding代码

参考
https://community.idera.com/developer-tools/b/blog/posts/quickly-auto-generate-ios-osx-and-android-headers-for-delphi-and-c-builder

**Comment by Assuner-Lee** [comment]
看上去有点意思，大佬可以尝试 提个pr看看，非常欢迎更多人去增强这个库
